---
title: "Untitled"
author: "Tianshu Lu"
date: "2022-09-12"
output: html_document
---

```{r}
library(selectr)
library(rvest)
library(xml2)
library(rtweet) # for scraping tweets
library(wordcloud2) # for generating really cool looking wordclouds
library(tm) # for text minning
library(dplyr) # loads of fun stuff including piping
library(ROAuth)
library(jsonlite)
library(httpuv)
```



```{r}
api = read.csv('Twitter_API.txt')
```

```{r}
consumer_key = api[api["Type"]=="API Key"][2]
consumer_secret = api[api["Type"]=="API Key Secret"][2]
access_token = api[api["Type"]=="Access Token"][2]
access_token_secret = api[api["Type"]=="Access Token Secret"][2]
bearer_token = api[api["Type"]=="Bearer Token"][2]
```

```{r}
library(twitteR)
```

```{r}
requestURL='https://api.twitter.com/oauth/request_token'
accessURL='https://api.twitter.com/oauth/access_token'
authURL='https://api.twitter.com/oauth/authorize'
```

```{r}
s_key  = 'League of Legends'
n_tweets = 250 
```

```{r}
twitteR:::setup_twitter_oauth(consumer_key, consumer_secret,access_token,access_token_secret)
Search1<-twitteR::searchTwitter(s_key,n=n_tweets, since="2021-01-07")

TweetsDF<- twListToDF(Search1)
#(TweetsDF$text[1])
View(TweetsDF)
### Saving the tweets to file
```
```{r}
FName = "~/LOLexample.csv"
## Start the file
MyFile <- file(FName)
## Write Tweets to file
cat(unlist(TweetsDF), " ", file=MyFile, sep="\n")
close(MyFile)
```

